service: ${file(config.js):application}

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:GetObjectVersion
        - s3:DeleteObject
        - s3:DeleteObjectVersion
        - s3:ListBucket
      Resource: "arn:aws:s3:::${file(config.js):bucket}/${file(config.js):application}/*"

package:
  exclude:
    - "node_modules/**"

functions:

  create:
    handler: endpoints/create.handler
    events:
      - http: POST /create
  read:
    handler: endpoints/read.handler
    events:
      - http: POST /read
  update:
    handler: endpoints/update.handler
    events:
      - http: POST /update